-- Add color and styling columns to pdf_settings table
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS primary_color text DEFAULT '#2563eb';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS secondary_color text DEFAULT '#64748b';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS text_color text DEFAULT '#1f2937';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS border_color text DEFAULT '#e5e7eb';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS header_color text DEFAULT '#2563eb';

-- Add font and layout settings
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS font_family text DEFAULT 'helvetica';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS font_size text DEFAULT 'medium';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS line_spacing text DEFAULT 'normal';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS table_style text DEFAULT 'bordered';

-- Add logo and footer settings
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS logo_url text;
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS logo_size text DEFAULT 'medium';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS company_name_size text DEFAULT 'large';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS show_footer boolean DEFAULT true;
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS footer_text text DEFAULT 'Thank you for your business!';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS payment_terms text DEFAULT 'Payment is due within 30 days of invoice date.';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS footer_notes text DEFAULT 'This invoice was generated by FreelanceTrackr';

-- Add layout settings
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS page_margin text DEFAULT 'normal';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS header_height text DEFAULT 'medium';
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS footer_height text DEFAULT 'small';

-- Add user_id column if it doesn't exist (for the NOT NULL constraint)
ALTER TABLE pdf_settings ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES profiles(id) ON DELETE CASCADE;
