-- Update default value for footer_notes in pdf_settings
ALTER TABLE pdf_settings ALTER COLUMN footer_notes SET DEFAULT 'This invoice was generated by BillSense';

-- Update existing rows
UPDATE pdf_settings 
SET footer_notes = 'This invoice was generated by BillSense' 
WHERE footer_notes = 'This invoice was generated by FreelanceTrackr';
