import React, { useState, useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { Save, Upload, Eye, Download, Palette, Type, Layout, X } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'

interface PDFSettingsData {
  // Header settings
  show_logo: boolean
  logo_url: string
  logo_size: 'small' | 'medium' | 'large'
  header_color: string
  company_name_size: 'small' | 'medium' | 'large'

  // Body settings
  font_family: 'helvetica' | 'times' | 'courier'
  font_size: 'small' | 'medium' | 'large'
  line_spacing: 'compact' | 'normal' | 'relaxed'
  table_style: 'minimal' | 'bordered' | 'striped'

  // Footer settings
  show_footer: boolean
  footer_text: string
  payment_terms: string
  footer_notes: string

  // Colors and styling
  primary_color: string
  secondary_color: string
  text_color: string
  border_color: string

  // Layout
  page_margin: 'narrow' | 'normal' | 'wide'
  header_height: 'small' | 'medium' | 'large'
  footer_height: 'small' | 'medium' | 'large'
  template: 'invoma_classic' | 'invoma_modern'
}

export const PDFSettings: React.FC = () => {
  const { user } = useAuth()
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [settings, setSettings] = useState<PDFSettingsData | null>(null)
  const [showPreview, setShowPreview] = useState(false)

  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<PDFSettingsData>({
    defaultValues: {
      show_logo: true,
      logo_url: '',
      logo_size: 'medium',
      header_color: '#2563eb',
      company_name_size: 'large',
      font_family: 'helvetica',
      font_size: 'medium',
      line_spacing: 'normal',
      table_style: 'bordered',
      show_footer: true,
      footer_text: 'Thank you for your business!',
      payment_terms: 'Payment is due within 30 days of invoice date.',
      footer_notes: 'This invoice was generated by BillSense',
      primary_color: '#2563eb',
      secondary_color: '#64748b',
      text_color: '#1f2937',
      border_color: '#e5e7eb',
      page_margin: 'normal',
      header_height: 'medium',
      footer_height: 'small',
      template: 'invoma_classic'
    }
  })

  const watchedSettings = watch()

  useEffect(() => {
    if (user) {
      loadPDFSettings()
    }
  }, [user])

  const loadPDFSettings = async () => {
    try {
      // First get the user's company_id
      const { data: profile, error: profileError } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user!.id)
        .single()

      if (profileError) throw profileError

      const { data, error } = await supabase
        .from('pdf_settings')
        .select('*')
        .eq('company_id', profile.company_id)
        .maybeSingle()

      if (error && error.code !== 'PGRST116') throw error

      if (data) {
        console.log('Loading PDF settings from database:', data)
        // Map the database columns to the form fields - use actual database values
        const mappedData = {
          show_logo: data.show_logo ?? true,
          logo_url: data.logo_url || '',
          logo_size: data.logo_size || 'medium',
          header_color: data.header_color || '#2563eb',
          company_name_size: data.company_name_size || 'large',
          font_family: data.font_family || 'helvetica',
          font_size: data.font_size || 'medium',
          line_spacing: data.line_spacing || 'normal',
          table_style: data.table_style || 'bordered',
          show_footer: data.show_footer ?? true,
          footer_text: data.footer_text || 'Thank you for your business!',
          payment_terms: data.payment_terms || 'Payment is due within 30 days of invoice date.',
          footer_notes: data.footer_notes || 'This invoice was generated by BillSense',
          primary_color: data.primary_color || '#2563eb',
          secondary_color: data.secondary_color || '#64748b',
          text_color: data.text_color || '#1f2937',
          border_color: data.border_color || '#e5e7eb',
          page_margin: data.page_margin || 'normal',
          header_height: data.header_height || 'medium',
          footer_height: data.footer_height || 'small',
          template: data.template || 'invoma_classic'
        }
        console.log('Mapped settings to form:', mappedData)
        setSettings(mappedData as PDFSettingsData)
        Object.keys(mappedData).forEach(key => {
          setValue(key as keyof PDFSettingsData, mappedData[key as keyof typeof mappedData])
        })
      }
    } catch (error) {
      console.error('Error loading PDF settings:', error)
    } finally {
      setLoading(false)
    }
  }

  const onSubmit = async (data: PDFSettingsData) => {
    setSaving(true)
    try {
      // Get the user's company_id
      const { data: profile, error: profileError } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user!.id)
        .single()

      if (profileError) {
        console.error('Profile error:', profileError)
        throw profileError
      }

      if (!profile.company_id) {
        alert('No company found. Please complete company setup first.')
        return
      }

      const settingsData = {
        company_id: profile.company_id,
        user_id: user!.id,
        // Template
        template: data.template,
        // Logo and header
        show_logo: data.show_logo,
        logo_url: data.logo_url || null,
        logo_size: data.logo_size,
        company_name_size: data.company_name_size,
        header_color: data.header_color,
        // Fonts and styling
        font_family: data.font_family,
        font_size: data.font_size,
        line_spacing: data.line_spacing,
        table_style: data.table_style,
        // Colors
        primary_color: data.primary_color,
        secondary_color: data.secondary_color,
        text_color: data.text_color,
        border_color: data.border_color,
        // Footer
        show_footer: data.show_footer,
        footer_text: data.footer_text,
        payment_terms: data.payment_terms,
        footer_notes: data.footer_notes,
        // Layout
        page_margin: data.page_margin,
        header_height: data.header_height,
        footer_height: data.footer_height,
        // Signature (defaults)
        show_signature: false,
        signature_url: null,
        custom_css: null
      }

      console.log('Attempting to save PDF settings:', settingsData)

      let result
      if (settings) {
        console.log('Updating existing settings for company:', profile.company_id)
        result = await supabase
          .from('pdf_settings')
          .update(settingsData)
          .eq('company_id', profile.company_id)
      } else {
        console.log('Inserting new settings for company:', profile.company_id)
        result = await supabase
          .from('pdf_settings')
          .insert(settingsData)
      }

      console.log('Save result:', result)

      if (result.error) {
        console.error('Database error:', result.error)
        throw result.error
      }

      setSettings(data)
      alert('PDF settings saved successfully!')
    } catch (error) {
      console.error('Error saving PDF settings:', error)
      alert('Failed to save PDF settings. Check console for details.')
      alert('Failed to save PDF settings')
    } finally {
      setSaving(false)
    }
  }

  const resetToDefaults = () => {
    const defaults = {
      show_logo: true,
      logo_url: '',
      logo_size: 'medium' as const,
      header_color: '#2563eb',
      company_name_size: 'large' as const,
      font_family: 'helvetica' as const,
      font_size: 'medium' as const,
      line_spacing: 'normal' as const,
      table_style: 'bordered' as const,
      show_footer: true,
      footer_text: 'Thank you for your business!',
      payment_terms: 'Payment is due within 30 days of invoice date.',
      footer_notes: 'This invoice was generated by BillSense',
      primary_color: '#2563eb',
      secondary_color: '#64748b',
      text_color: '#1f2937',
      border_color: '#e5e7eb',
      page_margin: 'normal' as const,
      header_height: 'medium' as const,
      footer_height: 'small' as const,
      template: 'invoma_classic' as const
    }

    Object.keys(defaults).forEach(key => {
      setValue(key as keyof PDFSettingsData, defaults[key as keyof typeof defaults])
    })
  }

  if (loading) {
    return (
      <div className="animate-pulse space-y-6">
        <div className="h-6 bg-gray-200 rounded w-1/4"></div>
        <div className="space-y-4">
          {[...Array(8)].map((_, i) => (
            <div key={i} className="h-10 bg-gray-200 rounded"></div>
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-medium text-gray-900">PDF Invoice Design</h3>
          <p className="mt-1 text-sm text-gray-600">
            Customize the appearance of your PDF invoices
          </p>
        </div>
        <div className="flex space-x-3">
          <button
            onClick={() => setShowPreview(true)}
            className="flex items-center px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
          >
            <Eye className="h-4 w-4 mr-2" />
            Preview
          </button>
          <button
            onClick={resetToDefaults}
            className="flex items-center px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
          >
            Reset to Defaults
          </button>
        </div>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-8">
        {/* Template Selection */}
        <div className="bg-white p-6 rounded-lg border border-gray-200">
          <div className="flex items-center mb-4">
            <Layout className="h-5 w-5 text-gray-400 mr-2" />
            <h4 className="text-md font-medium text-gray-900">Template Selection</h4>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[
              { value: 'invoma_classic', label: 'Invoma Classic', description: 'Clean layout with logo, invoice details, and organized sections' },
              { value: 'invoma_modern', label: 'Invoma Modern', description: 'Detailed company info with boxed invoice details' }
            ].map((template) => (
              <label
                key={template.value}
                className={`relative border-2 rounded-lg p-4 cursor-pointer hover:border-blue-500 transition-all ${watchedSettings.template === template.value ? 'border-blue-600 bg-blue-50' : 'border-gray-200'
                  }`}
              >
                <input
                  {...register('template')}
                  type="radio"
                  value={template.value}
                  className="sr-only"
                />
                <div className="text-center">
                  <div className="h-32 bg-gradient-to-br from-blue-50 to-indigo-50 mb-3 rounded border border-blue-200 flex items-center justify-center">
                    <div className="text-blue-600 text-sm font-medium px-4 text-center">
                      {template.label}
                    </div>
                  </div>
                  <span className="font-medium text-gray-900">{template.label}</span>
                  <p className="text-xs text-gray-500 mt-1">{template.description}</p>
                </div>
                {watchedSettings.template === template.value && (
                  <div className="absolute top-2 right-2 h-4 w-4 bg-blue-600 rounded-full"></div>
                )}
              </label>
            ))}
          </div>
        </div>

        {/* Header Settings */}
        <div className="bg-white p-6 rounded-lg border border-gray-200">
          <div className="flex items-center mb-4">
            <Layout className="h-5 w-5 text-gray-400 mr-2" />
            <h4 className="text-md font-medium text-gray-900">Header Settings</h4>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="md:col-span-2">
              <div className="flex items-center mb-4">
                <input
                  {...register('show_logo')}
                  type="checkbox"
                  className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                />
                <label className="ml-2 block text-sm text-gray-900">
                  Show company logo
                </label>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Logo URL
              </label>
              <input
                {...register('logo_url')}
                type="url"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="https://example.com/logo.png"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Logo Size
              </label>
              <select
                {...register('logo_size')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="small">Small</option>
                <option value="medium">Medium</option>
                <option value="large">Large</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Header Color
              </label>
              <input
                {...register('header_color')}
                type="color"
                className="w-full h-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Company Name Size
              </label>
              <select
                {...register('company_name_size')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="small">Small</option>
                <option value="medium">Medium</option>
                <option value="large">Large</option>
              </select>
            </div>
          </div>
        </div>

        {/* Body Settings */}
        <div className="bg-white p-6 rounded-lg border border-gray-200">
          <div className="flex items-center mb-4">
            <Type className="h-5 w-5 text-gray-400 mr-2" />
            <h4 className="text-md font-medium text-gray-900">Body Settings</h4>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Font Family
              </label>
              <select
                {...register('font_family')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="helvetica">Helvetica</option>
                <option value="times">Times New Roman</option>
                <option value="courier">Courier</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Font Size
              </label>
              <select
                {...register('font_size')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="small">Small</option>
                <option value="medium">Medium</option>
                <option value="large">Large</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Line Spacing
              </label>
              <select
                {...register('line_spacing')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="compact">Compact</option>
                <option value="normal">Normal</option>
                <option value="relaxed">Relaxed</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Table Style
              </label>
              <select
                {...register('table_style')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="minimal">Minimal</option>
                <option value="bordered">Bordered</option>
                <option value="striped">Striped</option>
              </select>
            </div>
          </div>
        </div>

        {/* Footer Settings */}
        <div className="bg-white p-6 rounded-lg border border-gray-200">
          <div className="flex items-center mb-4">
            <Layout className="h-5 w-5 text-gray-400 mr-2" />
            <h4 className="text-md font-medium text-gray-900">Footer Settings</h4>
          </div>

          <div className="space-y-4">
            <div className="flex items-center">
              <input
                {...register('show_footer')}
                type="checkbox"
                className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
              />
              <label className="ml-2 block text-sm text-gray-900">
                Show footer
              </label>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Footer Text
              </label>
              <input
                {...register('footer_text')}
                type="text"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Thank you for your business!"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Payment Terms
              </label>
              <textarea
                {...register('payment_terms')}
                rows={2}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Payment is due within 30 days of invoice date."
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Footer Notes
              </label>
              <input
                {...register('footer_notes')}
                type="text"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="This invoice was generated by BillSense"
              />
            </div>
          </div>
        </div>

        {/* Colors and Styling */}
        <div className="bg-white p-6 rounded-lg border border-gray-200">
          <div className="flex items-center mb-4">
            <Palette className="h-5 w-5 text-gray-400 mr-2" />
            <h4 className="text-md font-medium text-gray-900">Colors & Styling</h4>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Primary Color
              </label>
              <input
                {...register('primary_color')}
                type="color"
                className="w-full h-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Secondary Color
              </label>
              <input
                {...register('secondary_color')}
                type="color"
                className="w-full h-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Text Color
              </label>
              <input
                {...register('text_color')}
                type="color"
                className="w-full h-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Border Color
              </label>
              <input
                {...register('border_color')}
                type="color"
                className="w-full h-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
          </div>
        </div>

        {/* Layout Settings */}
        <div className="bg-white p-6 rounded-lg border border-gray-200">
          <div className="flex items-center mb-4">
            <Layout className="h-5 w-5 text-gray-400 mr-2" />
            <h4 className="text-md font-medium text-gray-900">Layout Settings</h4>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Page Margin
              </label>
              <select
                {...register('page_margin')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="narrow">Narrow</option>
                <option value="normal">Normal</option>
                <option value="wide">Wide</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Header Height
              </label>
              <select
                {...register('header_height')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="small">Small</option>
                <option value="medium">Medium</option>
                <option value="large">Large</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Footer Height
              </label>
              <select
                {...register('footer_height')}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="small">Small</option>
                <option value="medium">Medium</option>
                <option value="large">Large</option>
              </select>
            </div>
          </div>
        </div>

        {/* Save Button */}
        <div className="flex justify-end pt-4 border-t border-gray-200">
          <button
            type="submit"
            disabled={saving}
            className="flex items-center px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {saving ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                Saving...
              </>
            ) : (
              <>
                <Save className="h-4 w-4 mr-2" />
                Save PDF Settings
              </>
            )}
          </button>
        </div>
      </form>

      {/* Preview Modal */}
      {showPreview && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-6 border-b border-gray-200">
              <h2 className="text-xl font-semibold text-gray-900">PDF Preview</h2>
              <button
                onClick={() => setShowPreview(false)}
                className="p-2 text-gray-400 hover:text-gray-600 transition-colors"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
            <div className="p-6">
              <div className="bg-white border border-gray-300 rounded-lg p-8 shadow-sm">
                {/* Preview content based on current settings */}
                <div
                  className="border-b-4 pb-6 mb-6"
                  style={{ borderColor: watchedSettings.header_color }}
                >
                  <div className="flex items-center justify-between">
                    <div>
                      {watchedSettings.show_logo && watchedSettings.logo_url && (
                        <img
                          src={watchedSettings.logo_url}
                          alt="Logo"
                          className={`mb-2 ${watchedSettings.logo_size === 'small' ? 'h-8' :
                            watchedSettings.logo_size === 'medium' ? 'h-12' : 'h-16'
                            }`}
                        />
                      )}
                      <h1
                        className={`font-bold ${watchedSettings.company_name_size === 'small' ? 'text-lg' :
                          watchedSettings.company_name_size === 'medium' ? 'text-xl' : 'text-2xl'
                          }`}
                        style={{ color: watchedSettings.text_color }}
                      >
                        Your Company Name
                      </h1>
                    </div>
                    <div className="text-right">
                      <h2 className="text-3xl font-bold" style={{ color: watchedSettings.primary_color }}>
                        INVOICE
                      </h2>
                      <p className="text-gray-600">#INV-0001</p>
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-8 mb-8">
                  <div>
                    <h3 className="font-semibold mb-2" style={{ color: watchedSettings.secondary_color }}>
                      From:
                    </h3>
                    <p style={{ color: watchedSettings.text_color }}>Your Company Name</p>
                    <p style={{ color: watchedSettings.text_color }}>your@email.com</p>
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2" style={{ color: watchedSettings.secondary_color }}>
                      Bill To:
                    </h3>
                    <p style={{ color: watchedSettings.text_color }}>Client Name</p>
                    <p style={{ color: watchedSettings.text_color }}>client@email.com</p>
                  </div>
                </div>

                <table
                  className={`w-full mb-6 ${watchedSettings.table_style === 'bordered' ? 'border border-gray-300' :
                    watchedSettings.table_style === 'striped' ? '' : ''
                    }`}
                  style={{ borderColor: watchedSettings.border_color }}
                >
                  <thead>
                    <tr
                      className={watchedSettings.table_style === 'striped' ? 'bg-gray-50' : ''}
                      style={{ backgroundColor: watchedSettings.table_style === 'striped' ? '#f9fafb' : 'transparent' }}
                    >
                      <th className="text-left p-3 font-semibold" style={{ color: watchedSettings.secondary_color }}>
                        Description
                      </th>
                      <th className="text-center p-3 font-semibold" style={{ color: watchedSettings.secondary_color }}>
                        Qty
                      </th>
                      <th className="text-right p-3 font-semibold" style={{ color: watchedSettings.secondary_color }}>
                        Amount
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className={watchedSettings.table_style === 'bordered' ? 'border-t' : ''}>
                      <td className="p-3" style={{ color: watchedSettings.text_color }}>
                        Sample Service
                      </td>
                      <td className="p-3 text-center" style={{ color: watchedSettings.text_color }}>
                        1
                      </td>
                      <td className="p-3 text-right" style={{ color: watchedSettings.text_color }}>
                        $1,000.00
                      </td>
                    </tr>
                  </tbody>
                </table>

                <div className="flex justify-end mb-8">
                  <div className="w-64">
                    <div className="flex justify-between mb-2">
                      <span style={{ color: watchedSettings.secondary_color }}>Subtotal:</span>
                      <span style={{ color: watchedSettings.text_color }}>$1,000.00</span>
                    </div>
                    <div className="flex justify-between font-bold text-lg border-t pt-2">
                      <span style={{ color: watchedSettings.text_color }}>Total:</span>
                      <span style={{ color: watchedSettings.primary_color }}>$1,000.00</span>
                    </div>
                  </div>
                </div>

                {watchedSettings.show_footer && (
                  <div className="border-t pt-6" style={{ borderColor: watchedSettings.border_color }}>
                    <div className="text-center space-y-2">
                      <p className="font-medium" style={{ color: watchedSettings.text_color }}>
                        {watchedSettings.footer_text}
                      </p>
                      <p className="text-sm" style={{ color: watchedSettings.secondary_color }}>
                        {watchedSettings.payment_terms}
                      </p>
                      <p className="text-xs" style={{ color: watchedSettings.secondary_color }}>
                        {watchedSettings.footer_notes}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}